name: Validate Flare Prompt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Cancel in-progress runs on subsequent pushes to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Zig
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install zig
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install zig
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo snap install zig --beta --classic
          else
            echo "Unsupported runner OS"
            exit 1
          fi
        shell: bash

      - name: Validate Flare loads successfully
        shell: pwsh
        run: |
          # Import the module
          Import-Module ${{ github.workspace }}/flare.psm1 -ErrorAction Stop

          # Verify module was imported successfully
          if ($?) {
            Write-Host "✅ Flare prompt module loaded successfully on ${{ runner.os }}"
          } else {
            Write-Host "❌ Failed to load Flare prompt module on ${{ runner.os }}"
            exit 1
          }

      - name: Validate all Flare pieces work correctly
        shell: pwsh
        run: |
          # Run the testPiecesTiming.ps1 script which will validate all pieces
          # The script will exit with a non-zero code if any piece fails to load or execute correctly
          Write-Host "Running piece validation test on ${{ runner.os }}..."
          & ${{ github.workspace }}/testPiecesTiming.ps1

          if ($?) {
            Write-Host "✅ All Flare pieces validated successfully on ${{ runner.os }}"
          } else {
            Write-Host "❌ Flare piece validation failed on ${{ runner.os }}"
            exit 1
          }

      - name: Test Git piece functionality
        shell: pwsh
        run: |
          # Run comprehensive git piece tests covering all git states
          Write-Host "Running git piece functionality tests on ${{ runner.os }}..."
          & ${{ github.workspace }}/testGitStates.ps1

          if ($?) {
            Write-Host "✅ Git piece tests passed successfully on ${{ runner.os }}"
          } else {
            Write-Host "❌ Git piece tests failed on ${{ runner.os }}"
            exit 1
          }
